spring.application.name=Lab7
server.port=8080
#H2 database
spring.datasource.url=jdbc:h2:mem:lab7db
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
#H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true

#Jackson
#kh\uFFFDng tr? v? c\uFFFDc tr??ng null trong JSON response
spring.jackson.default-property-inclusion=NON_NULL

# T\u1EAFt log l\u1ED7i favicon cho g\u1ECDn console
logging.level.org.springframework.web.servlet.resource=OFF