spring.application.name=Lab7
server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1444;databaseName=lab7db;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Sontran1903@
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true

# T\u1EAFt log l\u1ED7i favicon cho g\u1ECDn console
logging.level.org.springframework.web.servlet.resource=OFF